Repository TEAM-HOUME/HOUME-SERVER, pull requests merged in 2025-09, with the labels that each got.

#229 [FEATURE] 어드민 가구 기능 구현
  src/main/java/or/sopt/houme/domain/admin/controller/AdminController.java
  src/main/java/or/sopt/houme/domain/admin/controller/AdminFurnitureController.java
  src/main/java/or/sopt/houme/domain/admin/controller/dto/furniture/AdminFurnitureDeleteDTO.java
  src/main/java/or/sopt/houme/domain/admin/controller/dto/furniture/AdminFurnitureDetailsRequestDTO.java
  src/main/java/or/sopt/houme/domain/admin/controller/dto/furniture/AdminFurnitureDetailsResponseDTO.java
  src/main/java/or/sopt/houme/domain/admin/controller/dto/furniture/AdminFurnitureGetDTO.java
  src/main/java/or/sopt/houme/domain/admin/controller/dto/furniture/AdminFurniturePromptRequestDTO.java
  src/main/java/or/sopt/houme/domain/admin/controller/dto/furniture/AdminFurnitureRequestDTO.java
  src/main/java/or/sopt/houme/domain/admin/controller/dto/furniture/AdminFurnitureTagDeleteDTO.java
  src/main/java/or/sopt/houme/domain/admin/controller/dto/furniture/AdminFurnitureTagGetDTO.java
  src/main/java/or/sopt/houme/domain/admin/controller/dto/furniture/AdminFurnitureUpdateRequestDTO.java
  src/main/java/or/sopt/houme/domain/admin/service/AdminFurnitureService.java
  src/main/java/or/sopt/houme/domain/admin/service/AdminFurnitureServiceImpl.java
  src/main/java/or/sopt/houme/domain/furniture/entity/Furniture.java
  src/main/java/or/sopt/houme/domain/furniture/entity/FurnitureTag.java
  src/main/java/or/sopt/houme/domain/furniture/repository/FurnitureRepository.java
  src/main/java/or/sopt/houme/domain/furniture/repository/FurnitureTagRepository.java
  src/main/java/or/sopt/houme/global/api/ErrorCode.java
  src/main/java/or/sopt/houme/global/config/SecurityConfig.java
  src/main/resources/templates/admin/dashboard.html
Labels: ✨ feat, ✊ 재연

#232 [HOTFIX] 스레드 풀 감축
  src/main/java/or/sopt/houme/global/config/AsyncConfig.java
Labels: :hammer_and_wrench: fix, ✊ 채륜

#234 [REFACTOR] 이미지 생성 컨트롤러 책임 분리 (v1, v2, v3, fallback)
  src/main/java/or/sopt/houme/domain/credit/service/CreditServiceImpl.java
  src/main/java/or/sopt/houme/domain/generateImage/controller/GenerateImageController.java
  src/main/java/or/sopt/houme/domain/generateImage/facade/GenerateImageFacade.java
  src/main/java/or/sopt/houme/domain/generateImage/service/GenerateImageService.java
  src/main/java/or/sopt/houme/global/api/ErrorCode.java
  src/main/java/or/sopt/houme/global/api/GlobalExceptionHandler.java
  src/main/java/or/sopt/houme/global/api/handler/ImageFallbackException.java
Labels: :recycle: refactor, ✊ 채륜

#243 [FEAT] admin 테스트 코드 & 주석 및 예외처리 추가
  src/main/java/or/sopt/houme/domain/admin/controller/dto/AdminTagUpdateRequestDTO.java
  src/main/java/or/sopt/houme/domain/admin/controller/dto/moodboard/AdminMoodBoardGetResponseDTO.java
  src/main/java/or/sopt/houme/domain/admin/service/AdminFurnitureServiceImpl.java
  src/main/java/or/sopt/houme/domain/admin/service/AdminMoodBoardServiceImpl.java
  src/main/java/or/sopt/houme/domain/admin/service/AdminTagServiceImpl.java
  src/main/java/or/sopt/houme/domain/furniture/entity/Furniture.java
  src/main/java/or/sopt/houme/domain/furniture/entity/FurnitureTag.java
  src/main/java/or/sopt/houme/domain/furniture/repository/FurnitureCustomRepository.java
  src/main/java/or/sopt/houme/domain/furniture/repository/FurnitureCustomRepositoryImpl.java
  src/main/java/or/sopt/houme/domain/furniture/repository/FurnitureRepository.java
  src/main/java/or/sopt/houme/domain/taste/entity/Tag.java
  src/main/java/or/sopt/houme/domain/taste/entity/Taste.java
  src/main/java/or/sopt/houme/domain/taste/entity/TasteTag.java
  src/main/java/or/sopt/houme/domain/taste/repository/tag/TagRepository.java
  src/main/java/or/sopt/houme/global/api/ErrorCode.java
  src/main/java/or/sopt/houme/global/util/S3PresignedUtil.java
  src/test/java/or/sopt/houme/domain/admin/controller/AdminFurnitureControllerTest.java
  src/test/java/or/sopt/houme/domain/admin/controller/AdminMoodBoardControllerTest.java
  src/test/java/or/sopt/houme/domain/admin/controller/AdminTagControllerTest.java
  src/test/java/or/sopt/houme/domain/admin/service/AdminFurnitureServiceImplTest.java
  src/test/java/or/sopt/houme/domain/admin/service/AdminMoodBoardServiceImplTest.java
  src/test/java/or/sopt/houme/domain/admin/service/AdminTagServiceImplTest.java
Labels: :m: test, ✨ feat, :1234: chore, ✊ 재연

#249 [REFACTOR] 프롬프트 좋아요 로직 수정
  .DS_Store
  src/main/java/or/sopt/houme/domain/carousel/controller/CarouselController.java
  src/main/java/or/sopt/houme/domain/carousel/facade/CarouselOptimisticLockFacade.java
  src/main/java/or/sopt/houme/domain/house/HouseLikeFacade.java
  src/main/java/or/sopt/houme/domain/house/controller/HouseController.java
  src/main/java/or/sopt/houme/domain/preference/entity/PromptPreference.java
  src/main/java/or/sopt/houme/domain/preference/repository/PromptPreferenceRepository.java
  src/main/java/or/sopt/houme/domain/preference/service/PromptPreferenceService.java
  src/main/java/or/sopt/houme/domain/preference/service/PromptPreferenceServiceImpl.java
  src/main/java/or/sopt/houme/global/api/ErrorCode.java
  src/test/java/or/sopt/houme/domain/preference/service/PromptPreferenceServiceImplTest.java
Labels: :recycle: refactor, :1234: chore, ✊ 채륜

#250 [FEATURE] 선호 여부에 따른 요인 문구 조회 및 토글 API
  src/main/java/or/sopt/houme/domain/preference/controller/FactorController.java
  src/main/java/or/sopt/houme/domain/preference/dto/response/FactorsResponse.java
  src/main/java/or/sopt/houme/domain/preference/entity/Factor.java
  src/main/java/or/sopt/houme/domain/preference/entity/PreferenceFactor.java
  src/main/java/or/sopt/houme/domain/preference/repository/FactorRepository.java
  src/main/java/or/sopt/houme/domain/preference/repository/FactorRepositoryCustom.java
  src/main/java/or/sopt/houme/domain/preference/repository/FactorRepositoryImpl.java
  src/main/java/or/sopt/houme/domain/preference/repository/PreferenceFactorRepository.java
  src/main/java/or/sopt/houme/domain/preference/service/FactorService.java
  src/main/java/or/sopt/houme/domain/preference/service/FactorServiceImpl.java
  src/main/java/or/sopt/houme/global/api/ErrorCode.java
  src/main/java/or/sopt/houme/global/api/handler/PreferenceException.java
  src/test/java/or/sopt/houme/domain/factor/controller/FactorControllerTest.java
  src/test/java/or/sopt/houme/domain/factor/repository/FactorRepositoryImplTest.java
  src/test/java/or/sopt/houme/domain/factor/service/FactorServiceImplTest.java
Labels: :m: test, ✨ feat

#255 [REFACTOR] 주요활동 내용 변경, 가구 카테고리 추가 및 DB 구조 변경
  src/main/java/or/sopt/houme/domain/furniture/dto/FurnitureItem.java
  src/main/java/or/sopt/houme/domain/furniture/dto/response/FurnitureAndActivityResponse.java
  src/main/java/or/sopt/houme/domain/furniture/dto/response/FurnitureCategoryGroup.java
  src/main/java/or/sopt/houme/domain/furniture/entity/FurnitureType.java
  src/main/java/or/sopt/houme/domain/furniture/service/FurnitureServiceImpl.java
  src/main/java/or/sopt/houme/domain/house/entity/enums/Activity.java
  src/test/java/or/sopt/houme/domain/admin/service/AdminFurnitureServiceImplTest.java
  src/test/java/or/sopt/houme/domain/furniture/service/FurnitureServiceImplTest.java
  src/test/java/or/sopt/houme/domain/generateImage/facade/GenerateImageFacadeTest.java
  src/test/java/or/sopt/houme/domain/generateImage/repository/GenerateImageRepositoryImplTest.java
  src/test/java/or/sopt/houme/domain/house/repository/HouseCustomRepositoryImplTest.java
  src/test/java/or/sopt/houme/domain/house/service/HouseServiceImplTest.java
  src/test/java/or/sopt/houme/domain/taste/repository/TagRepositoryImplTest.java
  src/test/java/or/sopt/houme/domain/user/repository/UserRepositoryImplTest.java
Labels: :recycle: refactor, ✊ 채륜

#257 [REFACTOR] 이미지 생성 Request 구조 변경 (bedId 삭제)
  src/main/java/or/sopt/houme/domain/furniture/service/FurnitureService.java
  src/main/java/or/sopt/houme/domain/furniture/service/FurnitureServiceImpl.java
  src/main/java/or/sopt/houme/domain/generateImage/dto/request/GenerateImageRequest.java
  src/main/java/or/sopt/houme/domain/generateImage/facade/GenerateImageFacade.java
  src/test/java/or/sopt/houme/domain/generateImage/facade/GenerateImageFacadeTest.java
Labels: :recycle: refactor, ✊ 채륜

#258 [FEATURE] 이미지에서 인식된 가구와 선택된 가구의 교집합으로 조회하는 가구 카테고리 API
  src/main/java/or/sopt/houme/domain/furniture/controller/FurnitureController.java
  src/main/java/or/sopt/houme/domain/furniture/dto/response/FurnitureCategoriesResponse.java
  src/main/java/or/sopt/houme/domain/furniture/entity/Furniture.java
  src/main/java/or/sopt/houme/domain/furniture/entity/FurnitureTag.java
  src/main/java/or/sopt/houme/domain/furniture/repository/FurnitureCustomRepository.java
  src/main/java/or/sopt/houme/domain/furniture/repository/FurnitureCustomRepositoryImpl.java
  src/main/java/or/sopt/houme/domain/furniture/repository/FurnitureTagRepository.java
  src/main/java/or/sopt/houme/domain/furniture/service/FurnitureService.java
  src/main/java/or/sopt/houme/domain/furniture/service/FurnitureServiceImpl.java
  src/test/java/or/sopt/houme/domain/furniture/service/FurnitureServiceImplTest.java
Labels: :m: test, ✨ feat, ✊ 본탁
