Repository TEAM-HOUME/HOUME-SERVER, pull requests merged in 2025-07, with the labels that each got.

#20 [FEATURE] develop-ci 파이프라인 완성
  .github/workflows/develop-ci.yml
  build.gradle
Labels: ✨ feat

#31 [FEATURE] jib 이미지 빌드 및 ecr 이미지 업로드
  .github/workflows/develop-ci.yml
  build.gradle
Labels: ✨ feat

#27 [FEATURE] 로그아웃 로직 구현
  src/main/java/or/sopt/houme/domain/user/controller/OAuthController.java
  src/main/java/or/sopt/houme/domain/user/repository/BlacklistTokenRepository.java
  src/main/java/or/sopt/houme/domain/user/service/OAuthService.java
  src/main/java/or/sopt/houme/global/api/ErrorCode.java
  src/main/java/or/sopt/houme/global/config/SecurityConfig.java
  src/main/java/or/sopt/houme/global/jwt/JWTFilter.java
  src/main/java/or/sopt/houme/global/jwt/JWTUtil.java
  src/main/java/or/sopt/houme/global/jwt/JWTUtilImpl.java
Labels: ✨ feat

#29 [FEATURE] jib gradle 설정 및 ecr 업로드 성공
  .github/workflows/develop-ci.yml
  build.gradle
Labels: ✨ feat

#34 [FEATURE] ERD 기반 도메인 및 BaseEntity 구현
  .gitignore
  src/main/java/or/sopt/houme/HoumeApplication.java
  src/main/java/or/sopt/houme/domain/carousel/entity/Carousel.java
  src/main/java/or/sopt/houme/domain/credit/entity/Credit.java
  src/main/java/or/sopt/houme/domain/credit/entity/CreditStatus.java
  src/main/java/or/sopt/houme/domain/floorPlan/entity/FloorPlan.java
  src/main/java/or/sopt/houme/domain/furniture/entity/BedType.java
  src/main/java/or/sopt/houme/domain/furniture/entity/ClosetType.java
  src/main/java/or/sopt/houme/domain/furniture/entity/Furniture.java
  src/main/java/or/sopt/houme/domain/furniture/entity/SelectiveFurnitureType.java
  src/main/java/or/sopt/houme/domain/generatedImage/entity/GenerateImage.java
  src/main/java/or/sopt/houme/domain/generatedImage/entity/Type.java
  src/main/java/or/sopt/houme/domain/house/entity/Activity.java
  src/main/java/or/sopt/houme/domain/house/entity/Equilibrium.java
  src/main/java/or/sopt/houme/domain/house/entity/Form.java
  src/main/java/or/sopt/houme/domain/house/entity/House.java
  src/main/java/or/sopt/houme/domain/house/entity/HouseFloorPlan.java
  src/main/java/or/sopt/houme/domain/house/entity/HouseFurniture.java
  src/main/java/or/sopt/houme/domain/house/entity/HouseTaste.java
  src/main/java/or/sopt/houme/domain/house/entity/Structure.java
  src/main/java/or/sopt/houme/domain/preference/entity/CarouselPreference.java
  src/main/java/or/sopt/houme/domain/preference/entity/Preference.java
  src/main/java/or/sopt/houme/domain/preference/entity/PromptPreference.java
  src/main/java/or/sopt/houme/domain/taste/entity/Tag.java
  src/main/java/or/sopt/houme/domain/taste/entity/Taste.java
  src/main/java/or/sopt/houme/domain/taste/entity/TasteTag.java
  src/main/java/or/sopt/houme/domain/user/entity/Gender.java
  src/main/java/or/sopt/houme/domain/user/entity/User.java
  src/main/java/or/sopt/houme/domain/user/entity/UserStatus.java
  src/main/java/or/sopt/houme/global/entity/BaseEntity.java
  src/main/resources/application-local.yml
Labels: ✨ feat

#38 [FIX] jpaauditing config 분리 및 test 프로필에선 막기
  src/main/java/or/sopt/houme/HoumeApplication.java
  src/main/java/or/sopt/houme/global/config/JpaAuditingConfig.java
Labels: ✨ feat

#36 [FEAT] develop cd 구성완료
  .github/workflows/develop-cd.yml
  .github/workflows/develop-ci.yml
  .gitignore
  build.gradle
  src/main/java/or/sopt/houme/HoumeApplication.java
  src/main/java/or/sopt/houme/global/api/HealthCheckController.java
  src/main/java/or/sopt/houme/global/config/JpaAuditingConfig.java
  src/main/java/or/sopt/houme/global/config/WhiteListConfig.java
  src/main/resources/application-local.yml
  src/test/java/or/sopt/houme/global/api/HealthCheckControllerTest.java
Labels: ✨ feat

#39 [FIX] develop CD docekr login 정보 수정
  .github/workflows/develop-cd.yml
Labels: :hammer_and_wrench: fix, ✨ feat, ✊ 채륜

#47 [FEAT] 집 구조 리스트 제공 API 개발
  src/main/java/or/sopt/houme/domain/house/controller/HouseController.java
  src/main/java/or/sopt/houme/domain/house/dto/HouseOptionDTO.java
  src/main/java/or/sopt/houme/domain/house/dto/response/HouseOptionsResponse.java
  src/main/java/or/sopt/houme/domain/house/service/HouseService.java
  src/main/java/or/sopt/houme/domain/house/service/HouseServiceImpl.java
  src/main/java/or/sopt/houme/global/config/SecurityConfig.java
  src/main/java/or/sopt/houme/global/config/WhiteListConfig.java
  src/test/java/or/sopt/houme/domain/house/controller/HouseControllerTest.java
  src/test/java/or/sopt/houme/domain/house/service/HouseServiceImplTest.java
Labels: ✨ feat, ✊ 채륜

#51 [FEAT] 집 구조 선택 API 개발
  src/main/java/or/sopt/houme/domain/house/controller/HouseController.java
  src/main/java/or/sopt/houme/domain/house/dto/request/HouseSelectRequest.java
  src/main/java/or/sopt/houme/domain/house/entity/HouseFurniture.java
  src/main/java/or/sopt/houme/domain/house/entity/InvalidHouseRequest.java
  src/main/java/or/sopt/houme/domain/house/entity/enums/Activity.java
  src/main/java/or/sopt/houme/domain/house/entity/enums/Equilibrium.java
  src/main/java/or/sopt/houme/domain/house/entity/enums/Form.java
  src/main/java/or/sopt/houme/domain/house/entity/enums/Structure.java
  src/main/java/or/sopt/houme/domain/house/entity/mapping/HouseFloorPlan.java
  src/main/java/or/sopt/houme/domain/house/entity/mapping/HouseFurniture.java
  src/main/java/or/sopt/houme/domain/house/entity/mapping/HouseTaste.java
  src/main/java/or/sopt/houme/domain/house/repository/HouseRepository.java
  src/main/java/or/sopt/houme/domain/house/repository/InvalidHouseRequestRepository.java
  src/main/java/or/sopt/houme/domain/house/service/HouseService.java
  src/main/java/or/sopt/houme/domain/house/service/HouseServiceImpl.java
  src/main/java/or/sopt/houme/domain/user/service/OAuthService.java
  src/main/java/or/sopt/houme/global/api/ErrorCode.java
  src/main/java/or/sopt/houme/global/config/WhiteListConfig.java
  src/test/java/or/sopt/houme/domain/house/controller/HouseControllerTest.java
  src/test/java/or/sopt/houme/domain/house/service/HouseServiceImplTest.java
Labels: ✨ feat, :1234: chore, ✊ 채륜

#58 [FIX] CD 워크플로우 skip 상태 추가
  .github/workflows/develop-cd.yml
Labels: :hammer_and_wrench: fix, ✊ 채륜

#56 [FIX] CI 워크플로우에 skip 상태 추가
  .github/workflows/develop-ci.yml
Labels: :hammer_and_wrench: fix, ✊ 채륜

#59 [FEATURE] QueryDSL 주입
  .gitignore
  build.gradle
Labels: ✨ feat, ✊ 재연

#73 Fix/#68/social hotfix
  src/main/java/or/sopt/houme/domain/user/service/OAuthService.java
Labels: :hammer_and_wrench: fix

#76 [CHORE] 엔티티 수정
  src/main/java/or/sopt/houme/domain/carousel/entity/Carousel.java
  src/main/java/or/sopt/houme/domain/floorPlan/entity/FloorPlan.java
  src/main/java/or/sopt/houme/domain/furniture/entity/Furniture.java
  src/main/java/or/sopt/houme/domain/generatedImage/entity/GenerateImage.java
  src/main/java/or/sopt/houme/domain/house/entity/House.java
  src/main/java/or/sopt/houme/domain/taste/entity/Taste.java
Labels: :1234: chore, ✊ 재연

#78 [FIX] access-token 헤더 추가
  src/main/java/or/sopt/houme/global/config/SecurityConfig.java
Labels: :hammer_and_wrench: fix, ✊ 재연

#79 [FEAT] 자신의 집과 유사한 도면 템플릿 이미지 제공
  .github/workflows/develop-cd.yml
  src/main/java/or/sopt/houme/domain/floorPlan/controller/FloorPlanController.java
  src/main/java/or/sopt/houme/domain/floorPlan/dto/response/FloorPlanListResponse.java
  src/main/java/or/sopt/houme/domain/floorPlan/dto/response/FloorPlanResponse.java
  src/main/java/or/sopt/houme/domain/floorPlan/entity/FloorPlan.java
  src/main/java/or/sopt/houme/domain/floorPlan/facade/FloorPlanFacade.java
  src/main/java/or/sopt/houme/domain/floorPlan/repository/FloorPlanCustomRepository.java
  src/main/java/or/sopt/houme/domain/floorPlan/repository/FloorPlanCustomRepositoryImpl.java
  src/main/java/or/sopt/houme/domain/floorPlan/repository/FloorPlanRepository.java
  src/main/java/or/sopt/houme/domain/floorPlan/service/FloorPlanService.java
  src/main/java/or/sopt/houme/domain/floorPlan/service/FloorPlanServiceImpl.java
  src/main/java/or/sopt/houme/domain/house/controller/HouseController.java
  src/main/java/or/sopt/houme/domain/house/dto/LatestHouseConditionDTO.java
  src/main/java/or/sopt/houme/domain/house/repository/HouseCustomRepository.java
  src/main/java/or/sopt/houme/domain/house/repository/HouseCustomRepositoryImpl.java
  src/main/java/or/sopt/houme/domain/house/repository/HouseRepository.java
  src/main/java/or/sopt/houme/domain/house/service/HouseService.java
  src/main/java/or/sopt/houme/domain/house/service/HouseServiceImpl.java
  src/main/java/or/sopt/houme/global/api/ErrorCode.java
  src/main/resources/application-local.yml
  src/test/java/or/sopt/houme/domain/floorPlan/service/FloorPlanServiceImplTest.java
  src/test/java/or/sopt/houme/domain/house/service/HouseServiceImplTest.java
  src/test/java/or/sopt/houme/facade/FloorPlanFacadeTest.java
Labels: :hammer_and_wrench: fix, ✨ feat, ✊ 채륜

#85 [HOTFIX] cd 테스트 v1
  .github/workflows/develop-cd.yml
  src/main/java/or/sopt/houme/domain/floorPlan/controller/FloorPlanController.java
Labels: :hammer_and_wrench: fix, ✊ 채륜

#92 [FIX] 메인 브랜치 수정
  src/main/java/or/sopt/houme/global/api/ErrorCode.java
Labels: :hammer_and_wrench: fix, ✊ 채륜, ✊ 재연

#95 [CHORE] LLM 응답 DTO 수정
  src/main/java/or/sopt/houme/domain/openai/controller/OpenAiController.java
  src/main/java/or/sopt/houme/domain/openai/controller/dto/OpenAiResponse.java
  src/main/java/or/sopt/houme/domain/openai/service/OpenAiServiceImpl.java
Labels: :1234: chore, ✊ 재연

#99 [FEAT] cursor기반 무드보드 제공 API 개발
  build.gradle
  src/main/java/or/sopt/houme/domain/address/controller/AddressController.java
  src/main/java/or/sopt/houme/domain/taste/controller/TasteController.java
  src/main/java/or/sopt/houme/domain/taste/dto/response/MoodBoardListResponse.java
  src/main/java/or/sopt/houme/domain/taste/dto/response/MoodBoardResponse.java
  src/main/java/or/sopt/houme/domain/taste/repository/TasteCustomRepository.java
  src/main/java/or/sopt/houme/domain/taste/repository/TasteCustomRepositoryImpl.java
  src/main/java/or/sopt/houme/domain/taste/repository/TasteRepository.java
  src/main/java/or/sopt/houme/domain/taste/service/TasteService.java
  src/main/java/or/sopt/houme/domain/taste/service/TasteServiceImpl.java
  src/main/java/or/sopt/houme/global/api/ErrorCode.java
  src/main/java/or/sopt/houme/global/api/GlobalExceptionHandler.java
  src/main/java/or/sopt/houme/global/config/WhiteListConfig.java
  src/test/java/or/sopt/houme/domain/taste/service/TasteServiceImplTest.java
Labels: ✨ feat, :1234: chore, ✊ 채륜, ✊ 본탁

#101 [FEATURE] 마이페이지에서 이미지 생성 이력 클릭시 결과 페이지 제공 API
  src/main/java/or/sopt/houme/domain/generateImage/entity/GenerateImage.java
  src/main/java/or/sopt/houme/domain/generateImage/entity/Type.java
  src/main/java/or/sopt/houme/domain/generateImage/repository/GenerateImageRepository.java
  src/main/java/or/sopt/houme/domain/generateImage/repository/GenerateImageRepositoryCustom.java
  src/main/java/or/sopt/houme/domain/generateImage/repository/GenerateImageRepositoryImpl.java
  src/main/java/or/sopt/houme/domain/house/entity/House.java
  src/main/java/or/sopt/houme/domain/house/repository/HouseCustomRepository.java
  src/main/java/or/sopt/houme/domain/house/repository/HouseCustomRepositoryImpl.java
  src/main/java/or/sopt/houme/domain/taste/repository/TagRepository.java
  src/main/java/or/sopt/houme/domain/taste/repository/TagRepositoryCustom.java
  src/main/java/or/sopt/houme/domain/taste/repository/TagRepositoryImpl.java
  src/main/java/or/sopt/houme/domain/user/controller/UserController.java
  src/main/java/or/sopt/houme/domain/user/controller/dto/ImageHistoryResultPageResponse.java
  src/main/java/or/sopt/houme/domain/user/repository/UserRepositoryCustom.java
  src/main/java/or/sopt/houme/domain/user/repository/UserRepositoryImpl.java
  src/main/java/or/sopt/houme/domain/user/service/UserService.java
  src/main/java/or/sopt/houme/domain/user/service/UserServiceImpl.java
  src/main/java/or/sopt/houme/global/api/ErrorCode.java
  src/main/java/or/sopt/houme/global/api/handler/GenerateImageException.java
  src/main/java/or/sopt/houme/global/api/handler/HouseException.java
  src/main/java/or/sopt/houme/global/api/handler/TagException.java
  src/test/java/or/sopt/houme/domain/generateImage/repository/GenerateImageRepositoryImplTest.java
  src/test/java/or/sopt/houme/domain/house/repository/HouseCustomRepositoryImplTest.java
  src/test/java/or/sopt/houme/domain/taste/repository/TagRepositoryImplTest.java
  src/test/java/or/sopt/houme/domain/user/controller/UserControllerTest.java
  src/test/java/or/sopt/houme/domain/user/repository/UserRepositoryImplTest.java
  src/test/java/or/sopt/houme/domain/user/service/UserServiceImplTest.java
  src/test/java/or/sopt/houme/domain/user/service/UserServiceTest.java
Labels: ✨ feat, :1234: chore, ✊ 본탁

#106 [FEATURE] 충전하기 버튼 클릭 로그 저장
  src/main/java/or/sopt/houme/domain/credit/controller/PaymentBtnClickLogController.java
  src/main/java/or/sopt/houme/domain/credit/entity/PaymentBtnClickLog.java
  src/main/java/or/sopt/houme/domain/credit/repository/PaymentBtnClickLogRepository.java
  src/main/java/or/sopt/houme/domain/credit/service/PaymentBtnClickLogService.java
  src/main/java/or/sopt/houme/global/config/WhiteListConfig.java
Labels: ✨ feat, ✊ 본탁

#109 [FIX] LLM 로그 추가
  src/main/java/or/sopt/houme/domain/openai/service/OpenAiServiceImpl.java
Labels: :hammer_and_wrench: fix, ✊ 재연

#113 [FEATURE] 테스트 추가 및 크레딧 생성로직 구현
  build.gradle
  src/main/java/or/sopt/houme/domain/credit/repository/CreditRepository.java
  src/main/java/or/sopt/houme/domain/openai/controller/dto/OpenAiResponse.java
  src/main/java/or/sopt/houme/domain/user/controller/dto/KaKaoOAuthTokenDTO.java
  src/main/java/or/sopt/houme/domain/user/controller/dto/KaKaoUserInfoResponse.java
  src/main/java/or/sopt/houme/domain/user/service/OAuthService.java
  src/main/java/or/sopt/houme/domain/user/service/UserServiceImpl.java
  src/main/java/or/sopt/houme/global/api/ErrorCode.java
  src/main/java/or/sopt/houme/global/api/handler/CreditException.java
  src/test/java/or/sopt/houme/domain/openai/controller/dto/OpenAiRequestTest.java
  src/test/java/or/sopt/houme/domain/openai/controller/dto/OpenAiResponseTest.java
  src/test/java/or/sopt/houme/domain/user/controller/JWTControllerTest.java
  src/test/java/or/sopt/houme/domain/user/controller/OAuthControllerTest.java
  src/test/java/or/sopt/houme/domain/user/controller/dto/CustomUserDetailsTest.java
  src/test/java/or/sopt/houme/domain/user/controller/dto/KaKaoCallbackResponseTest.java
  src/test/java/or/sopt/houme/domain/user/controller/dto/KaKaoUserInfoResponseTest.java
  src/test/java/or/sopt/houme/domain/user/service/JWTServiceTest.java
  src/test/java/or/sopt/houme/domain/user/service/OAuthServiceTest.java
  src/test/java/or/sopt/houme/domain/user/service/UserServiceImplTest.java
Labels: ✨ feat, :1234: chore, ✊ 재연, ✊ 본탁

#115 [FEATURE] 가구 추천받기 버튼 클릭 로그 저장
  src/main/java/or/sopt/houme/domain/credit/repository/PaymentBtnClickLogRepository.java
  src/main/java/or/sopt/houme/domain/furniture/controller/FurnitureRecommendBtnClickLogController.java
  src/main/java/or/sopt/houme/domain/furniture/entity/FurnitureRecommendBtnClickLog.java
  src/main/java/or/sopt/houme/domain/furniture/repository/FurnitureRecommendBtnClickLogRepository.java
  src/main/java/or/sopt/houme/domain/furniture/service/FurnitureRecommendBtnClickLogService.java
Labels: ✨ feat, ✊ 본탁

#119 [FEATURE] Cookie 도메인 설정
  src/main/java/or/sopt/houme/global/util/CookieUtil.java
Labels: ✨ feat, ✊ 재연

#120 [FEAT] 이미지 생성 api
  src/main/java/or/sopt/houme/domain/credit/repository/CreditCustomRepository.java
  src/main/java/or/sopt/houme/domain/credit/repository/CreditCustomRepositoryImpl.java
  src/main/java/or/sopt/houme/domain/credit/repository/CreditRepository.java
  src/main/java/or/sopt/houme/domain/credit/service/CreditService.java
  src/main/java/or/sopt/houme/domain/credit/service/CreditServiceImpl.java
  src/main/java/or/sopt/houme/domain/generateImage/controller/GenerateImageController.java
  src/main/java/or/sopt/houme/domain/generateImage/dto/request/GenerateImageRequest.java
  src/main/java/or/sopt/houme/domain/generateImage/dto/response/ImageInfoResponse.java
  src/main/java/or/sopt/houme/domain/generateImage/entity/GenerateImage.java
  src/main/java/or/sopt/houme/domain/generateImage/entity/Type.java
  src/main/java/or/sopt/houme/domain/generateImage/facade/GenerateImageFacade.java
  src/main/java/or/sopt/houme/domain/generateImage/service/GenerateImageService.java
  src/main/java/or/sopt/houme/domain/generateImage/service/GenerateImageServiceImpl.java
  src/main/java/or/sopt/houme/domain/generatedImage/entity/Type.java
  src/main/java/or/sopt/houme/domain/house/entity/House.java
  src/main/java/or/sopt/houme/domain/house/service/HouseService.java
  src/main/java/or/sopt/houme/domain/house/service/HouseServiceImpl.java
  src/main/java/or/sopt/houme/domain/prompt/dto/PromptRequestDTO.java
  src/main/java/or/sopt/houme/domain/user/entity/User.java
  src/main/java/or/sopt/houme/global/api/ErrorCode.java
  src/test/java/or/sopt/houme/domain/generateImage/repository/GenerateImageRepositoryImplTest.java
  src/test/java/or/sopt/houme/domain/generateImage/service/GenerateImageServiceImplTest.java
  src/test/java/or/sopt/houme/domain/house/repository/HouseCustomRepositoryImplTest.java
  src/test/java/or/sopt/houme/domain/house/service/HouseServiceImplTest.java
  src/test/java/or/sopt/houme/domain/openai/facade/OpenAiFacadeTest.java
  src/test/java/or/sopt/houme/domain/prompt/service/PromptServiceImplTest.java
  src/test/java/or/sopt/houme/domain/taste/repository/TagRepositoryImplTest.java
  src/test/java/or/sopt/houme/domain/user/repository/UserRepositoryImplTest.java
Labels: ✨ feat, :1234: chore, ✊ 채륜

#122 [FEAT] 이미지 좋아요 API
  src/main/java/or/sopt/houme/domain/generateImage/controller/GenerateImageController.java
  src/main/java/or/sopt/houme/domain/generateImage/service/GenerateImageService.java
  src/main/java/or/sopt/houme/domain/generateImage/service/GenerateImageServiceImpl.java
  src/main/java/or/sopt/houme/domain/house/HouseLikeFacade.java
  src/main/java/or/sopt/houme/domain/house/controller/HouseController.java
  src/main/java/or/sopt/houme/domain/house/dto/request/IsLikeRequest.java
  src/main/java/or/sopt/houme/domain/house/service/HouseService.java
  src/main/java/or/sopt/houme/domain/house/service/HouseServiceImpl.java
  src/main/java/or/sopt/houme/domain/preference/entity/PromptPreference.java
  src/main/java/or/sopt/houme/domain/preference/service/PreferenceService.java
  src/main/java/or/sopt/houme/domain/preference/service/PreferenceServiceImpl.java
  src/main/java/or/sopt/houme/domain/preference/service/PromptPreferenceService.java
  src/main/java/or/sopt/houme/domain/preference/service/PromptPreferenceServiceImpl.java
  src/test/java/or/sopt/houme/domain/generateImage/service/GenerateImageServiceImplTest.java
  src/test/java/or/sopt/houme/domain/house/controller/HouseControllerTest.java
  src/test/java/or/sopt/houme/domain/preference/service/PreferenceServiceImplTest.java
  src/test/java/or/sopt/houme/domain/preference/service/PromptPreferenceServiceImplTest.java
Labels: ✨ feat, :1234: chore, ✊ 채륜

#124 [FIX] houseId response
  src/main/java/or/sopt/houme/domain/house/controller/HouseController.java
  src/main/java/or/sopt/houme/domain/house/dto/response/HouseIdResponse.java
  src/main/java/or/sopt/houme/domain/house/service/HouseService.java
  src/main/java/or/sopt/houme/domain/house/service/HouseServiceImpl.java
Labels: :hammer_and_wrench: fix, ✊ 채륜

#126 [FEAT] 웹 배포 uri CORS 추가
  src/main/java/or/sopt/houme/global/config/SecurityConfig.java
Labels: ✨ feat, ✊ 재연

#139 [FIX] 컬럼 이름 수정 file_name -> filename
  src/main/java/or/sopt/houme/domain/carousel/entity/Carousel.java
  src/main/java/or/sopt/houme/domain/floorPlan/entity/FloorPlan.java
  src/main/java/or/sopt/houme/domain/generateImage/entity/GenerateImage.java
  src/main/java/or/sopt/houme/domain/taste/entity/Taste.java
Labels: :hammer_and_wrench: fix, :1234: chore, ✊ 채륜

#141 [FIX] code label로 필드명 수정
  src/main/java/or/sopt/houme/domain/furniture/dto/ActivityItem.java
  src/test/java/or/sopt/houme/domain/furniture/service/FurnitureServiceImplTest.java
Labels: :hammer_and_wrench: fix, :recycle: refactor, ✊ 채륜

#144 chore:#143 리다이렉트 uri 수정
  src/main/java/or/sopt/houme/HoumeApplication.java
Labels: :hammer_and_wrench: fix, :1234: chore, ✊ 재연

#145 [REFECTOR] 캐러셀(스택) 가구 타입별로 반환
  build.gradle
  src/main/java/or/sopt/houme/domain/carousel/controller/CarouselController.java
  src/main/java/or/sopt/houme/domain/carousel/controller/dto/GetCarouselResponseDTO.java
  src/main/java/or/sopt/houme/domain/carousel/entity/Carousel.java
  src/main/java/or/sopt/houme/domain/carousel/entity/CarouselTag.java
  src/main/java/or/sopt/houme/domain/carousel/entity/CarouselType.java
  src/main/java/or/sopt/houme/domain/carousel/service/CarouselServiceImpl.java
  src/main/java/or/sopt/houme/domain/floorPlan/entity/FloorPlan.java
  src/main/java/or/sopt/houme/domain/taste/entity/Tag.java
  src/main/java/or/sopt/houme/domain/taste/entity/Taste.java
  src/test/java/or/sopt/houme/domain/carousel/service/CarouselServiceImplTest.java
Labels: :recycle: refactor, :1234: chore, ✊ 채륜

#147 [FIX] description -> label로 변경
  src/main/java/or/sopt/houme/domain/house/dto/HouseOptionDTO.java
  src/test/java/or/sopt/houme/domain/house/controller/HouseControllerTest.java
Labels: :hammer_and_wrench: fix, :recycle: refactor, ✊ 채륜

#150 [FEATURE] 쿠키 도메인 분리
  src/main/java/or/sopt/houme/domain/user/controller/OAuthController.java
  src/main/java/or/sopt/houme/domain/user/service/JWTService.java
  src/main/java/or/sopt/houme/domain/user/service/OAuthService.java
  src/main/java/or/sopt/houme/domain/user/valid/RefreshTokenValidator.java
  src/main/java/or/sopt/houme/global/config/CookieConfig.java
  src/main/java/or/sopt/houme/global/util/CookieUtil.java
  src/main/resources/application-local.yml
  src/test/java/or/sopt/houme/domain/user/controller/OAuthControllerTest.java
  src/test/java/or/sopt/houme/domain/user/service/JWTServiceTest.java
  src/test/java/or/sopt/houme/domain/user/service/OAuthServiceTest.java
Labels: ✨ feat, :1234: chore, ✊ 재연

#152 [FIX] customuser service 추가
  src/main/java/or/sopt/houme/domain/user/controller/dto/CustomUserDetailsService.java
  src/main/java/or/sopt/houme/domain/user/repository/UserRepository.java
  src/main/java/or/sopt/houme/global/jwt/JWTFilter.java
  src/test/java/or/sopt/houme/domain/user/controller/UserControllerTest.java
Labels: :hammer_and_wrench: fix, ✊ 채륜

#154 [FIX] credit-status
  src/main/java/or/sopt/houme/domain/carousel/controller/CarouselController.java
  src/main/java/or/sopt/houme/domain/credit/repository/CreditCustomRepositoryImpl.java
Labels: :hammer_and_wrench: fix, :recycle: refactor, ✊ 채륜

#158 [REFECTOR] add reverse_prompt
  src/main/java/or/sopt/houme/domain/floorPlan/entity/FloorPlan.java
  src/test/java/or/sopt/houme/domain/floorPlan/service/FloorPlanServiceImplTest.java
Labels: :recycle: refactor, ✊ 채륜

#160 [REFECTOR] furniture_style_prompt
  src/main/java/or/sopt/houme/domain/furniture/entity/Furniture.java
  src/main/java/or/sopt/houme/domain/furniture/entity/FurnitureTag.java
  src/main/java/or/sopt/houme/domain/furniture/repository/FurnitureTagRepository.java
  src/main/java/or/sopt/houme/domain/prompt/service/PromptServiceImpl.java
  src/test/java/or/sopt/houme/domain/furniture/service/FurnitureServiceImplTest.java
  src/test/java/or/sopt/houme/domain/prompt/service/PromptServiceImplTest.java
Labels: :recycle: refactor, ✊ 채륜

#167 Fix/#164/options
  src/main/java/or/sopt/houme/domain/openai/client/FastApiImageClient.java
Labels: :hammer_and_wrench: fix

#171 [FIX] 도면 조건 structure로만 수정
  src/main/java/or/sopt/houme/domain/floorPlan/repository/FloorPlanCustomRepository.java
  src/main/java/or/sopt/houme/domain/floorPlan/repository/FloorPlanCustomRepositoryImpl.java
  src/main/java/or/sopt/houme/domain/floorPlan/service/FloorPlanServiceImpl.java
  src/main/java/or/sopt/houme/domain/generateImage/dto/request/GenerateImageRequest.java
  src/test/java/or/sopt/houme/domain/floorPlan/service/FloorPlanServiceImplTest.java
Labels: :hammer_and_wrench: fix, ✊ 채륜

#179 [FIX] #177 무드보드 랜덤 반환
  src/main/java/or/sopt/houme/domain/generateImage/dto/request/GenerateImageRequest.java
  src/main/java/or/sopt/houme/domain/taste/service/TasteServiceImpl.java
  src/test/java/or/sopt/houme/domain/taste/service/TasteServiceImplTest.java
Labels: :hammer_and_wrench: fix, ✊ 채륜

#189 [FIX] house-prompt 저장
  src/main/java/or/sopt/houme/domain/generateImage/facade/GenerateImageFacade.java
  src/main/java/or/sopt/houme/domain/house/entity/House.java
  src/main/java/or/sopt/houme/domain/house/service/HouseService.java
  src/main/java/or/sopt/houme/domain/house/service/HouseServiceImpl.java
  src/main/java/or/sopt/houme/domain/user/service/UserService.java
  src/main/java/or/sopt/houme/domain/user/service/UserServiceImpl.java
Labels: :hammer_and_wrench: fix, :recycle: refactor, ✊ 채륜

#191 [FEATURE] FAST-API fallback 로직 구현
  build.gradle
  src/main/java/or/sopt/houme/domain/generateImage/controller/GenerateImageController.java
  src/main/java/or/sopt/houme/domain/openai/controller/FastApiController.java
  src/main/java/or/sopt/houme/domain/openai/service/FastApiServiceImpl.java
  src/main/java/or/sopt/houme/domain/openai/service/OpenAiServiceImpl.java
  src/main/java/or/sopt/houme/domain/prompt/service/PromptServiceImpl.java
  src/main/java/or/sopt/houme/global/aop/CircuitBreakerLogger.java
  src/main/java/or/sopt/houme/global/api/ApiResponse.java
  src/main/java/or/sopt/houme/global/util/constant/S3Constant.java
  src/main/java/or/sopt/houme/global/util/constant/S3DirNameConstant.java
  src/main/resources/application-local.yml
Labels: :hammer_and_wrench: fix, :recycle: refactor, ✨ feat, :1234: chore, ✊ 재연

#193 [HOTFIX] 도면 제공 캐싱 제거
  src/main/java/or/sopt/houme/domain/floorPlan/facade/FloorPlanFacade.java
  src/main/java/or/sopt/houme/domain/floorPlan/service/FloorPlanServiceImpl.java
Labels: :hammer_and_wrench: fix, ✊ 채륜

#199 [FIX] #198 mapping-table
  src/main/java/or/sopt/houme/domain/generateImage/facade/GenerateImageFacade.java
  src/main/java/or/sopt/houme/domain/house/repository/HouseFloorPlanRepository.java
  src/main/java/or/sopt/houme/domain/house/repository/HouseFurnitureRepository.java
  src/main/java/or/sopt/houme/domain/house/repository/HouseTasteRepository.java
  src/main/java/or/sopt/houme/domain/house/service/HouseService.java
  src/main/java/or/sopt/houme/domain/house/service/HouseServiceImpl.java
Labels: :hammer_and_wrench: fix, :recycle: refactor, :1234: chore, ✊ 채륜

#201 [FIX] min, asc로 변경
  .github/workflows/develop-ci.yml
  src/main/java/or/sopt/houme/domain/carousel/service/CarouselCacheService.java
  src/main/java/or/sopt/houme/domain/carousel/service/CarouselService.java
  src/main/java/or/sopt/houme/domain/carousel/service/CarouselServiceImpl.java
  src/main/java/or/sopt/houme/domain/credit/service/CreditServiceImpl.java
  src/main/java/or/sopt/houme/domain/taste/repository/taste_tag/TasteTagCustomRepositoryImpl.java
  src/main/java/or/sopt/houme/domain/user/entity/User.java
  src/main/java/or/sopt/houme/domain/user/repository/UserRepositoryImpl.java
  src/test/java/or/sopt/houme/domain/carousel/service/CarouselServiceImplTest.java
  src/test/java/or/sopt/houme/domain/user/controller/UserControllerTest.java
  src/test/java/or/sopt/houme/domain/user/repository/UserRepositoryImplTest.java
Labels: :hammer_and_wrench: fix, :recycle: refactor, :1234: chore, ✊ 채륜

#205 [HOTFIX] 이미지 생성 조회 API 예외 추가
  src/main/java/or/sopt/houme/domain/house/entity/House.java
  src/main/java/or/sopt/houme/domain/house/repository/HouseCustomRepositoryImpl.java
  src/main/java/or/sopt/houme/domain/house/service/HouseServiceImpl.java
  src/main/java/or/sopt/houme/domain/user/repository/UserRepositoryCustom.java
  src/main/java/or/sopt/houme/domain/user/repository/UserRepositoryImpl.java
  src/test/java/or/sopt/houme/domain/generateImage/facade/GenerateImageFacadeTest.java
  src/test/java/or/sopt/houme/domain/generateImage/service/GenerateImageServiceImplTest.java
  src/test/java/or/sopt/houme/domain/user/repository/UserRepositoryImplTest.java
Labels: :hammer_and_wrench: fix, :1234: chore, ✊ 본탁

#212 [FEAT] 이미지 생성 중 fallback 생성
  src/main/java/or/sopt/houme/domain/generateImage/controller/GenerateImageController.java
  src/main/java/or/sopt/houme/domain/generateImage/facade/GenerateImageFacade.java
  src/main/java/or/sopt/houme/domain/generateImage/service/GenerateImageService.java
  src/main/java/or/sopt/houme/domain/generateImage/service/GenerateImageServiceImpl.java
  src/main/java/or/sopt/houme/domain/house/repository/HouseFloorPlanRepository.java
  src/main/java/or/sopt/houme/domain/house/service/HouseService.java
  src/main/java/or/sopt/houme/domain/house/service/HouseServiceImpl.java
  src/main/java/or/sopt/houme/domain/taste/service/TagService.java
  src/main/java/or/sopt/houme/domain/taste/service/TagServiceImpl.java
  src/main/java/or/sopt/houme/domain/user/repository/UserRepositoryImpl.java
  src/main/java/or/sopt/houme/global/api/ErrorCode.java
Labels: :hammer_and_wrench: fix, :recycle: refactor, ✨ feat, :1234: chore, ✊ 채륜

#213 [HOTFIX] 이미지 이력 클릭시 결과페이지 api 수정
  src/main/java/or/sopt/houme/domain/taste/repository/tag/TagRepositoryImpl.java
Labels: :hammer_and_wrench: fix, ✊ 본탁

#218 [FEATURE] 이미지 이력 결과 페이지 제공 API에 좋아요 여부 추가
  src/main/java/or/sopt/houme/domain/preference/repository/PreferenceRepository.java
  src/main/java/or/sopt/houme/domain/preference/repository/PreferenceRepositoryCustom.java
  src/main/java/or/sopt/houme/domain/preference/repository/PreferenceRepositoryImpl.java
  src/main/java/or/sopt/houme/domain/user/controller/dto/ImageHistoryResultPageResponse.java
  src/main/java/or/sopt/houme/domain/user/service/UserServiceImpl.java
  src/test/java/or/sopt/houme/domain/user/service/UserServiceImplTest.java
Labels: ✨ feat, :1234: chore, ✊ 재연

#220 [FIX] #219 이미지 좋아요 조회 로직 수정
  src/main/java/or/sopt/houme/domain/preference/repository/PromptPreferenceRepository.java
  src/main/java/or/sopt/houme/domain/user/service/UserServiceImpl.java
  src/test/java/or/sopt/houme/domain/user/service/UserServiceImplTest.java
Labels: :hammer_and_wrench: fix, :1234: chore, ✊ 채륜, ✊ 재연
